/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-08 14:27:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/header.jsp", Long.valueOf(1694136940693L));
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/footer.jsp", Long.valueOf(1694137028338L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/admin/goodsEnroll.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css\" />\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.ckeditor.com/ckeditor5/39.0.1/classic/ckeditor.js\"></script>\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.8.18/jquery-ui.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" 				\r\n");
      out.write(" 				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <!-- gnv_area -->    \r\n");
      out.write("            <div class=\"top_gnb_area\">\r\n");
      out.write("                <ul class=\"list\">    \r\n");
      out.write("                    <li><a href=\"/main\">메인 페이지</a></li>\r\n");
      out.write("                    <li><a href=\"/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("                    <li>고객센터</li>            \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- top_subject_area -->\r\n");
      out.write("            <div class=\"admin_top_wrap\">\r\n");
      out.write("                <span>관리자 페이지</span>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- contents-area -->\r\n");
      out.write("            <div class=\"admin_wrap\">\r\n");
      out.write("                <!-- 네비영역 -->\r\n");
      out.write("                <div class=\"admin_navi_wrap\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                      <li >\r\n");
      out.write("                          <a class=\"admin_list_01\" href=\"/admin/goodsEnroll\">상품 등록</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <a class=\"admin_list_02\" href=\"/admin/goodsManage\">상품 관리</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_03\" href=\"/admin/authorEnroll\">작가 등록</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_04\" href=\"/admin/authorManage\">작가 관리</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_05\">회원 관리</a>                            \r\n");
      out.write("                      </lI>                                                                                             \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"admin_content_wrap\">\r\n");
      out.write("                    <div class=\"admin_content_subject\"><span>상품 등록</span></div>\r\n");
      out.write("                    <div class=\"admin_content_main\">\r\n");
      out.write("                    	<form action=\"/admin/goodsEnroll\" method=\"post\" id=\"enrollForm\">\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 제목</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"bookName\">\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>작가</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input id=\"authorName_input\" readonly=\"readonly\" />\r\n");
      out.write("                    				<input id = \"authorId_input\" name=\"authorId\" type=\"hidden\">\r\n");
      out.write("                    				<button class=\"authorId_btn\">작가 선택</button>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>            \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>출판일</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"publeYear\" autocomplete =\"off\" readonly = \"readonly\">\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>            \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>출판사</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"publisher\">\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>             \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 카테고리</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("									<div class=\"cate_wrap\">\r\n");
      out.write("										<span>대분류</span>\r\n");
      out.write("										<select class=\"cate1\">\r\n");
      out.write("											<option selected value=\"none\">선택</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"cate_wrap\">\r\n");
      out.write("										<span>중분류</span>\r\n");
      out.write("										<select class=\"cate2\">\r\n");
      out.write("											<option selected value=\"none\">선택</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"cate_wrap\">\r\n");
      out.write("										<span>소분류</span>\r\n");
      out.write("										<select class=\"cate3\" name=\"cateCode\">\r\n");
      out.write("											<option selected value=\"none\">선택</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div> 	\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>          \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 가격</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"bookPrice\" value=\"0\">\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>               \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 재고</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"bookStock\" value=\"0\">\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>          \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 할인율</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"bookDiscount\" value=\"0\">\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>          		\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 소개</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<textarea name=\"bookIntro\" id=\"bookIntro_textarea\"></textarea>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>        		\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 목차</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<textarea name=\"bookContents\" id=\"bookContents_textarea\"></textarea>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                   		</form>\r\n");
      out.write("                   			<div class=\"btn_section\">\r\n");
      out.write("                   				<button id=\"cancelBtn\" class=\"btn\">취 소</button>\r\n");
      out.write("	                    		<button id=\"enrollBtn\" class=\"btn enroll_btn\">등 록</button>\r\n");
      out.write("	                    	</div> \r\n");
      out.write("                    </div>  \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        <!-- Footer 영역 -->\r\n");
      out.write("        <div class=\"footer_nav\">\r\n");
      out.write("            <div class=\"footer_nav_container\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>회사소개</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>이용약관</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>고객센터</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>광고문의</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>채용정보</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer_nav\" -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer_container\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer_left\">\r\n");
      out.write("                    <img src=\"resources/img/Logo.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_right\">\r\n");
      out.write("                    (주) JINI Books    대표이사 : OOO\r\n");
      out.write("                    <br>\r\n");
      out.write("                    사업자등록번호 : ooo-oo-ooooo\r\n");
      out.write("                    <br>\r\n");
      out.write("                    대표전화 : oooo-oooo(발신자 부담전화)\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    COPYRIGHT(C) <strong>kimvampa.tistory.com</strong>    ALL RIGHTS RESERVED.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer\" -->\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("	let enrollForm = $(\"#enrollForm\")\r\n");
      out.write("	\r\n");
      out.write("	/* 취소 버튼 */\r\n");
      out.write("	$(\"#cancelBtn\").click(function(){\r\n");
      out.write("		\r\n");
      out.write("		location.href=\"/admin/goodsManage\"\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 상품 등록 버튼 */\r\n");
      out.write("	$(\"#enrollBtn\").on(\"click\",function(e){\r\n");
      out.write("		\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		\r\n");
      out.write("		enrollForm.submit();\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 위지윅 적용 */\r\n");
      out.write("	 \r\n");
      out.write("	/* 책 소개 */\r\n");
      out.write("	ClassicEditor\r\n");
      out.write("		.create(document.querySelector('#bookIntro_textarea'))\r\n");
      out.write("		.catch(error=>{\r\n");
      out.write("			console.error(error);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	/* 책 목차 */	\r\n");
      out.write("	ClassicEditor\r\n");
      out.write("	.create(document.querySelector('#bookContents_textarea'))\r\n");
      out.write("	.catch(error=>{\r\n");
      out.write("		console.error(error);\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//캘린더 위젯 적용\r\n");
      out.write("	\r\n");
      out.write("	//설정\r\n");
      out.write("	const config = {\r\n");
      out.write("			dateFormat: 'yy-mm-dd',\r\n");
      out.write("			showOn : \"button\",\r\n");
      out.write("			buttonText : \"날짜 선택\",\r\n");
      out.write("			prevText: '이전 달',\r\n");
      out.write("		    nextText: '다음 달',\r\n");
      out.write("		    monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("		    monthNamesShort: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("		    dayNames: ['일','월','화','수','목','금','토'],\r\n");
      out.write("		    dayNamesShort: ['일','월','화','수','목','금','토'],\r\n");
      out.write("		    dayNamesMin: ['일','월','화','수','목','금','토'],\r\n");
      out.write("		    yearSuffix: '년',\r\n");
      out.write("		    changeMonth : true,\r\n");
      out.write("		    changeYear : true\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	//캘린더\r\n");
      out.write("	$(function(){\r\n");
      out.write("		\r\n");
      out.write("		$(\"input[name='publeYear']\").datepicker(config);\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 작가 선택 버튼 */\r\n");
      out.write("	$('.authorId_btn').on(\"click\",function(e){\r\n");
      out.write("		\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		\r\n");
      out.write("		let popUrl = \"/admin/authorPop\";\r\n");
      out.write("		let popOption = \"width = 650px, height=550px, top=300px, left=300px, scrollbars=yes\";\r\n");
      out.write("		\r\n");
      out.write("		window.open(popUrl,\"작가 찾기\",popOption);\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		console.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cateList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
