/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-11 03:17:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/header.jsp", Long.valueOf(1694136940693L));
    _jspx_dependants.put("jar:file:/C:/임베디드웹/shoppingMall/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1690855704120L));
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/footer.jsp", Long.valueOf(1694137028338L));
    _jspx_dependants.put("jar:file:/C:/임베디드웹/shoppingMall/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/admin/goodsDetail.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("	integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	#result_card img{\r\n");
      out.write("		max-width: 100%;\r\n");
      out.write("	    height: auto;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	    padding: 5px;\r\n");
      out.write("	    margin-top: 10px;\r\n");
      out.write("	    margin: auto;	\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <!-- gnv_area -->    \r\n");
      out.write("            <div class=\"top_gnb_area\">\r\n");
      out.write("                <ul class=\"list\">    \r\n");
      out.write("                    <li><a href=\"/main\">메인 페이지</a></li>\r\n");
      out.write("                    <li><a href=\"/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("                    <li>고객센터</li>            \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- top_subject_area -->\r\n");
      out.write("            <div class=\"admin_top_wrap\">\r\n");
      out.write("                <span>관리자 페이지</span>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- contents-area -->\r\n");
      out.write("            <div class=\"admin_wrap\">\r\n");
      out.write("                <!-- 네비영역 -->\r\n");
      out.write("                <div class=\"admin_navi_wrap\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                      <li >\r\n");
      out.write("                          <a class=\"admin_list_01\" href=\"/admin/goodsEnroll\">상품 등록</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <a class=\"admin_list_02\" href=\"/admin/goodsManage\">상품 관리</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_03\" href=\"/admin/authorEnroll\">작가 등록</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_04\" href=\"/admin/authorManage\">작가 관리</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_05\">회원 관리</a>                            \r\n");
      out.write("                      </lI>                                                                                             \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>");
      out.write("\r\n");
      out.write("	<div class=\"admin_content_wrap\">\r\n");
      out.write("		<div class=\"admin_content_subject\">\r\n");
      out.write("			<span>상품 상세</span>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"admin_content_main\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>책 제목</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input name=\"bookName\"\r\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\" disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>등록 날짜</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input\r\n");
      out.write("						value=\"");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>최근 수정 날짜</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input\r\n");
      out.write("						value=\"");
      if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>작가</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input id=\"authorName_input\" readonly=\"readonly\"\r\n");
      out.write("						value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.authorName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>출판일</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input name=\"publeYear\" autocomplete=\"off\" readonly=\"readonly\"\r\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\" disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>출판사</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input name=\"publisher\"\r\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\" disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>책 카테고리</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<div class=\"cate_wrap\">\r\n");
      out.write("						<span>대분류</span> <select class=\"cate1\" disabled>\r\n");
      out.write("							<option value=\"none\">선택</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"cate_wrap\">\r\n");
      out.write("						<span>중분류</span> <select class=\"cate2\" disabled>\r\n");
      out.write("							<option value=\"none\">선택</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"cate_wrap\">\r\n");
      out.write("						<span>소분류</span> <select class=\"cate3\" name=\"cateCode\" disabled>\r\n");
      out.write("							<option value=\"none\">선택</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>상품 가격</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input name=\"bookPrice\"\r\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("\" disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>상품 재고</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input name=\"bookStock\"\r\n");
      out.write("						value=\"");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("\" disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>상품 할인율</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("					<input id=\"discount_interface\" maxlength=\"2\" disabled>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>책 소개</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content bit\">\r\n");
      out.write("					<textarea name=\"bookIntro\" id=\"bookIntro_textarea\" disabled>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookIntro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>책 목차</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content bct\">\r\n");
      out.write("					<textarea name=\"bookContents\" id=\"bookContents_textarea\" disabled>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookContents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"form_section\">\r\n");
      out.write("				<div class=\"form_section_title\">\r\n");
      out.write("					<label>상품 이미지</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form_section_content\">\r\n");
      out.write("\r\n");
      out.write("					<div id=\"uploadReslut\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"btn_section\">\r\n");
      out.write("				<button id=\"cancelBtn\" class=\"btn\">상품 목록</button>\r\n");
      out.write("				<button id=\"modifyBtn\" class=\"btn modify_btn\">수정</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form id=\"moveForm\" action=\"/admin/goodsManage\" method=\"get\">\r\n");
      out.write("			<input type=\"hidden\" name=\"pageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input\r\n");
      out.write("				type=\"hidden\" name=\"amount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <input\r\n");
      out.write("				type=\"hidden\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        <!-- Footer 영역 -->\r\n");
      out.write("        <div class=\"footer_nav\">\r\n");
      out.write("            <div class=\"footer_nav_container\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>회사소개</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>이용약관</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>고객센터</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>광고문의</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>채용정보</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer_nav\" -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer_container\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer_left\">\r\n");
      out.write("                    <img src=\"resources/img/Logo.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_right\">\r\n");
      out.write("                    (주) JINI Books    대표이사 : OOO\r\n");
      out.write("                    <br>\r\n");
      out.write("                    사업자등록번호 : ooo-oo-ooooo\r\n");
      out.write("                    <br>\r\n");
      out.write("                    대표전화 : oooo-oooo(발신자 부담전화)\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    COPYRIGHT(C) <strong>kimvampa.tistory.com</strong>    ALL RIGHTS RESERVED.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer\" -->\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		//할인율 값 삽입\r\n");
      out.write("		let bookDiscount = '");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("' * 100;\r\n");
      out.write("		$(\"#discount_interface\").attr(\"value\", bookDiscount);\r\n");
      out.write("		\r\n");
      out.write("		/* 책 소개 */\r\n");
      out.write("		ClassicEditor\r\n");
      out.write("			.create(document.querySelector('#bookIntro_textarea'))\r\n");
      out.write("			.then(editor => {\r\n");
      out.write("				console.log(editor);\r\n");
      out.write("				editor.isReadOnly = true;\r\n");
      out.write("			})\r\n");
      out.write("			.catch(error=>{\r\n");
      out.write("				console.error(error);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("		/* 책 목차 */	\r\n");
      out.write("		ClassicEditor\r\n");
      out.write("		.create(document.querySelector('#bookContents_textarea'))\r\n");
      out.write("		.then(editor => {\r\n");
      out.write("			console.log(editor);\r\n");
      out.write("			editor.isReadOnly = true;\r\n");
      out.write("		})\r\n");
      out.write("		.catch(error=>{\r\n");
      out.write("			console.error(error);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		/* 카테고리 */\r\n");
      out.write("		let cateList = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cateList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("		let cate1Array = new Array();\r\n");
      out.write("		let cate2Array = new Array();\r\n");
      out.write("		let cate3Array = new Array();\r\n");
      out.write("		let cate1Obj = new Object();\r\n");
      out.write("		let cate2Obj = new Object();\r\n");
      out.write("		let cate3Obj = new Object();\r\n");
      out.write("		\r\n");
      out.write("		let cateSelect1 = $(\".cate1\");		\r\n");
      out.write("		let cateSelect2 = $(\".cate2\");\r\n");
      out.write("		let cateSelect3 = $(\".cate3\");\r\n");
      out.write("		\r\n");
      out.write("		/* 카테고리 배열 초기화 메서드 */\r\n");
      out.write("		function makeCateArray(obj,array,cateList, tier){\r\n");
      out.write("			for(let i = 0; i < cateList.length; i++){\r\n");
      out.write("				if(cateList[i].tier === tier){\r\n");
      out.write("					obj = new Object();\r\n");
      out.write("					\r\n");
      out.write("					obj.cateName = cateList[i].cateName;\r\n");
      out.write("					obj.cateCode = cateList[i].cateCode;\r\n");
      out.write("					obj.cateParent = cateList[i].cateParent;\r\n");
      out.write("					\r\n");
      out.write("					array.push(obj);				\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("		/* 배열 초기화 */\r\n");
      out.write("		makeCateArray(cate1Obj,cate1Array,cateList,1);\r\n");
      out.write("		makeCateArray(cate2Obj,cate2Array,cateList,2);\r\n");
      out.write("		makeCateArray(cate3Obj,cate3Array,cateList,3);\r\n");
      out.write("		\r\n");
      out.write("		let targetCate2 = '';\r\n");
      out.write("		let targetCate3 = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.cateCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		\r\n");
      out.write("		for(let i = 0; i < cate3Array.length; i++){\r\n");
      out.write("			if(targetCate3 == cate3Array[i].cateCode){\r\n");
      out.write("				targetCate3 = cate3Array[i];\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		for(let i =0; i<cate3Array.length; i++){\r\n");
      out.write("			if(targetCate3.cateParent == cate3Array[i].cateParent){\r\n");
      out.write("				cateSelect3.append(\"<option value='\"+cate3Array[i].cateCode+\"'>\"+cate3Array[i].cateName+\"</option>\");\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(\".cate3 option\").each(function(i,obj){\r\n");
      out.write("			if(targetCate3.cateCode === obj.value){\r\n");
      out.write("				$(obj).attr(\"selected\", \"selected\");\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		for(let i = 0; i < cate2Array.length; i++){\r\n");
      out.write("			if(targetCate3.cateParent === cate2Array[i].cateCode){\r\n");
      out.write("				targetCate2 = cate2Array[i];	\r\n");
      out.write("			}\r\n");
      out.write("		}// for	\r\n");
      out.write("		\r\n");
      out.write("		for(let i = 0; i < cate2Array.length; i++){\r\n");
      out.write("			if(targetCate2.cateParent === cate2Array[i].cateParent){\r\n");
      out.write("				cateSelect2.append(\"<option value='\"+cate2Array[i].cateCode+\"'>\" + cate2Array[i].cateName + \"</option>\");\r\n");
      out.write("			}\r\n");
      out.write("		}		\r\n");
      out.write("		\r\n");
      out.write("		$(\".cate2 option\").each(function(i,obj){\r\n");
      out.write("			if(targetCate2.cateCode === obj.value){\r\n");
      out.write("				$(obj).attr(\"selected\", \"selected\");\r\n");
      out.write("			}\r\n");
      out.write("		});	\r\n");
      out.write("		\r\n");
      out.write("		for(let i = 0; i < cate1Array.length; i++){\r\n");
      out.write("			cateSelect1.append(\"<option value='\"+cate1Array[i].cateCode+\"'>\" + cate1Array[i].cateName + \"</option>\");\r\n");
      out.write("		}\r\n");
      out.write("		$(\".cate1 option\").each(function(i,obj){\r\n");
      out.write("			if(targetCate2.cateParent === obj.value){\r\n");
      out.write("				$(obj).attr(\"selected\", \"selected\");\r\n");
      out.write("			}\r\n");
      out.write("		});	\r\n");
      out.write("		\r\n");
      out.write("		/* 이미지 정보 호출 */\r\n");
      out.write("		let bookId = '");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("		let uploadReslut = $(\"#uploadReslut\");\r\n");
      out.write("		\r\n");
      out.write("		$.getJSON(\"/getAttachList\", {bookId : bookId}, function(arr){\r\n");
      out.write("			\r\n");
      out.write("			if(arr.length === 0){	\r\n");
      out.write("				\r\n");
      out.write("				let str = \"\";\r\n");
      out.write("				str += \"<div id='result_card'>\";\r\n");
      out.write("				str += \"<img src='/resources/img/goodsNoImage.png'>\";\r\n");
      out.write("				str += \"</div>\";\r\n");
      out.write("				\r\n");
      out.write("				uploadReslut.html(str);	\r\n");
      out.write("				\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			let str = \"\";\r\n");
      out.write("			let obj = arr[0];\r\n");
      out.write("			\r\n");
      out.write("			let fileCallPath = encodeURIComponent(obj.uploadPath + \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("			str += \"<div id='result_card'\";\r\n");
      out.write("			str += \"data-path='\" + obj.uploadPath + \"' data-uuid='\" + obj.uuid + \"' data-filename='\" + obj.fileName + \"'\";\r\n");
      out.write("			str += \">\";\r\n");
      out.write("			str += \"<img src='/display?fileName=\" + fileCallPath +\"'>\";\r\n");
      out.write("			str += \"</div>\";\r\n");
      out.write("			\r\n");
      out.write("			uploadReslut.html(str);\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 목록 이동 버튼 */\r\n");
      out.write("	$(\"#cancelBtn\").on(\"click\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		$(\"#moveForm\").submit();	\r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("	/* 수정 페이지 이동 */\r\n");
      out.write("	$(\"#modifyBtn\").on(\"click\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		let addInput = '<input type=\"hidden\" name=\"bookId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">';\r\n");
      out.write("		$(\"#moveForm\").append(addInput);\r\n");
      out.write("		$(\"#moveForm\").attr(\"action\", \"/admin/goodsModify\");\r\n");
      out.write("		$(\"#moveForm\").submit();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(43,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(52,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.regDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/admin/goodsDetail.jsp(52,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(62,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.updateDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/admin/goodsDetail.jsp(62,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
      _jspx_th_fmt_005fformatDate_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(82,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.publeYear}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(91,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.publisher}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(122,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookPrice}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(131,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookStock}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(192,22) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookDiscount}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f6_reused = false;
    try {
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent(null);
      // /WEB-INF/views/admin/goodsDetail.jsp(302,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      _jspx_th_c_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f6_reused);
    }
    return false;
  }
}
