/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-11 03:34:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goodsModify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/header.jsp", Long.valueOf(1694136940693L));
    _jspx_dependants.put("jar:file:/C:/임베디드웹/shoppingMall/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1690855704120L));
    _jspx_dependants.put("/WEB-INF/views/admin/../includes/admin/footer.jsp", Long.valueOf(1694137028338L));
    _jspx_dependants.put("jar:file:/C:/임베디드웹/shoppingMall/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoppingMall/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/admin/goodsModify.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css\" />\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("  integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write(" <script src=\"https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js\"></script>\r\n");
      out.write(" <script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.8.18/jquery-ui.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("        <div class=\"wrap\">\r\n");
      out.write("            <!-- gnv_area -->    \r\n");
      out.write("            <div class=\"top_gnb_area\">\r\n");
      out.write("                <ul class=\"list\">    \r\n");
      out.write("                    <li><a href=\"/main\">메인 페이지</a></li>\r\n");
      out.write("                    <li><a href=\"/member/logout.do\">로그아웃</a></li>\r\n");
      out.write("                    <li>고객센터</li>            \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- top_subject_area -->\r\n");
      out.write("            <div class=\"admin_top_wrap\">\r\n");
      out.write("                <span>관리자 페이지</span>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- contents-area -->\r\n");
      out.write("            <div class=\"admin_wrap\">\r\n");
      out.write("                <!-- 네비영역 -->\r\n");
      out.write("                <div class=\"admin_navi_wrap\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                      <li >\r\n");
      out.write("                          <a class=\"admin_list_01\" href=\"/admin/goodsEnroll\">상품 등록</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li>\r\n");
      out.write("                          <a class=\"admin_list_02\" href=\"/admin/goodsManage\">상품 관리</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_03\" href=\"/admin/authorEnroll\">작가 등록</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_04\" href=\"/admin/authorManage\">작가 관리</a>                            \r\n");
      out.write("                      </lI>\r\n");
      out.write("                      <lI>\r\n");
      out.write("                          <a class=\"admin_list_05\">회원 관리</a>                            \r\n");
      out.write("                      </lI>                                                                                             \r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("                <div class=\"admin_content_wrap\">\r\n");
      out.write("                    <div class=\"admin_content_subject\"><span>상품 수정</span></div>\r\n");
      out.write("                    <div class=\"admin_content_main\">\r\n");
      out.write("                    	<form action=\"/admin/goodsModify\" method=\"post\" id=\"modifyForm\">\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 제목</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"bookName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    				<span class=\"ck_warn bookName_warn\">책 이름을 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>작가</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input id=\"authorName_input\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.authorName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    				<input id=\"authorId_input\" name=\"authorId\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.authorId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    				<button class=\"authorId_btn\">작가 선택</button>\r\n");
      out.write("                    				<span class=\"ck_warn authorId_warn\">작가를 선택해주세요</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>            \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>출판일</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"publeYear\" autocomplete=\"off\" readonly=\"readonly\">\r\n");
      out.write("                    				<span class=\"ck_warn publeYear_warn\">출판일을 선택해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>            \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>출판사</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"publisher\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.publisher}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    				<span class=\"ck_warn publisher_warn\">출판사를 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>             \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 카테고리</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<div class=\"cate_wrap\">\r\n");
      out.write("                    					<span>대분류</span>\r\n");
      out.write("                    					<select class=\"cate1\">\r\n");
      out.write("                    						<option selected value=\"none\">선택</option>\r\n");
      out.write("                    					</select>\r\n");
      out.write("                    				</div>\r\n");
      out.write("                    				<div class=\"cate_wrap\">\r\n");
      out.write("                    					<span>중분류</span>\r\n");
      out.write("                    					<select class=\"cate2\">\r\n");
      out.write("                    						<option selected value=\"none\">선택</option>\r\n");
      out.write("                    					</select>\r\n");
      out.write("                    				</div>\r\n");
      out.write("                    				<div class=\"cate_wrap\">\r\n");
      out.write("                    					<span>소분류</span>\r\n");
      out.write("                    					<select class=\"cate3\" name=\"cateCode\">\r\n");
      out.write("                    						<option selected value=\"none\">선택</option>\r\n");
      out.write("                    					</select>\r\n");
      out.write("                    				</div>  \r\n");
      out.write("                    				<span class=\"ck_warn cateCode_warn\">카테고리를 선택해주세요.</span>                  				                    				\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>          \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 가격</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"bookPrice\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    				<span class=\"ck_warn bookPrice_warn\">상품 가격을 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>               \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 재고</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input name=\"bookStock\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookStock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    				<span class=\"ck_warn bookStock_warn\">상품 재고를 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>          \r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 할인율</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("                    				<input id=\"discount_interface\" maxlength=\"2\" value=\"0\">\r\n");
      out.write("                    				<input name=\"bookDiscount\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookDiscount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    				<span class=\"step_val\">할인 가격 : <span class=\"span_discount\"></span></span>\r\n");
      out.write("                    				<span class=\"ck_warn bookDiscount_warn\">1~99 숫자를 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>          		\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 소개</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content bit\">\r\n");
      out.write("                    				<textarea name=\"bookIntro\" id=\"bookIntro_textarea\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookIntro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                    				<span class=\"ck_warn bookIntro_warn\">책 소개를 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>        		\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>책 목차</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content bct\">\r\n");
      out.write("                    				<textarea name=\"bookContents\" id=\"bookContents_textarea\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookContents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                    				<span class=\"ck_warn bookContents_warn\">책 목차를 입력해주세요.</span>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                    		<div class=\"form_section\">\r\n");
      out.write("                    			<div class=\"form_section_title\">\r\n");
      out.write("                    				<label>상품 이미지</label>\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    			<div class=\"form_section_content\">\r\n");
      out.write("									<input type=\"file\" id =\"fileItem\" name='uploadFile' style=\"height: 30px;\">\r\n");
      out.write("									<div id=\"uploadResult\">\r\n");
      out.write("																		\r\n");
      out.write("									</div>									\r\n");
      out.write("                    			</div>\r\n");
      out.write("                    		</div>\r\n");
      out.write("                    		<input type=\"hidden\" name='bookId' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                   		</form>\r\n");
      out.write("                   			<div class=\"btn_section\">\r\n");
      out.write("                   				<button id=\"cancelBtn\" class=\"btn\">취 소</button>\r\n");
      out.write("	                    		<button id=\"modifyBtn\" class=\"btn modify_btn\">수 정</button>\r\n");
      out.write("	                    		<button id=\"deleteBtn\" class=\"btn delete_btn\">삭 제</button>\r\n");
      out.write("	                    	</div> \r\n");
      out.write("                    </div>  \r\n");
      out.write("                	<form id=\"moveForm\" action=\"/admin/goodsManage\" method=\"get\" >\r\n");
      out.write(" 						<input type=\"hidden\" name=\"pageNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"amount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name='bookId' value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                	</form>                     \r\n");
      out.write("                </div>\r\n");
      out.write(" \r\n");
      out.write(" 				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("        <!-- Footer 영역 -->\r\n");
      out.write("        <div class=\"footer_nav\">\r\n");
      out.write("            <div class=\"footer_nav_container\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>회사소개</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>이용약관</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>고객센터</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>광고문의</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                    <li>채용정보</li>\r\n");
      out.write("                    <span class=\"line\">|</span>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer_nav\" -->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"footer\">\r\n");
      out.write("            <div class=\"footer_container\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer_left\">\r\n");
      out.write("                    <img src=\"resources/img/Logo.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer_right\">\r\n");
      out.write("                    (주) JINI Books    대표이사 : OOO\r\n");
      out.write("                    <br>\r\n");
      out.write("                    사업자등록번호 : ooo-oo-ooooo\r\n");
      out.write("                    <br>\r\n");
      out.write("                    대표전화 : oooo-oooo(발신자 부담전화)\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    COPYRIGHT(C) <strong>kimvampa.tistory.com</strong>    ALL RIGHTS RESERVED.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> <!-- class=\"footer\" -->\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write(" 				\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		$(document).ready(function(){\r\n");
      out.write("			\r\n");
      out.write("			/* 캘린더 위젯 적용 */\r\n");
      out.write("			/* 설정 */\r\n");
      out.write("			const config = {\r\n");
      out.write("				dateFormat: 'yy-mm-dd',\r\n");
      out.write("				showOn : \"button\",\r\n");
      out.write("				buttonText:\"날짜 선택\",\r\n");
      out.write("			    prevText: '이전 달',\r\n");
      out.write("			    nextText: '다음 달',\r\n");
      out.write("			    monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("			    monthNamesShort: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\r\n");
      out.write("			    dayNames: ['일','월','화','수','목','금','토'],\r\n");
      out.write("			    dayNamesShort: ['일','월','화','수','목','금','토'],\r\n");
      out.write("			    dayNamesMin: ['일','월','화','수','목','금','토'],\r\n");
      out.write("			    yearSuffix: '년',\r\n");
      out.write("		        changeMonth: true,\r\n");
      out.write("		        changeYear: true\r\n");
      out.write("			}			\r\n");
      out.write("			/* 캘린더 */\r\n");
      out.write("			$(function() {\r\n");
      out.write("				let publeYear = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.publeYear}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("			    $( \"input[name='publeYear']\" ).datepicker(config);\r\n");
      out.write("			    $( \"input[name='publeYear']\" ).datepicker('setDate', publeYear);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			/* 카테고리 */\r\n");
      out.write("			let cateList = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cateList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("			let cate1Array = new Array();\r\n");
      out.write("			let cate2Array = new Array();\r\n");
      out.write("			let cate3Array = new Array();\r\n");
      out.write("			let cate1Obj = new Object();\r\n");
      out.write("			let cate2Obj = new Object();\r\n");
      out.write("			let cate3Obj = new Object();\r\n");
      out.write("			\r\n");
      out.write("			let cateSelect1 = $(\".cate1\");		\r\n");
      out.write("			let cateSelect2 = $(\".cate2\");\r\n");
      out.write("			let cateSelect3 = $(\".cate3\");\r\n");
      out.write("			\r\n");
      out.write("			/* 카테고리 배열 초기화 메서드 */\r\n");
      out.write("			function makeCateArray(obj,array,cateList, tier){\r\n");
      out.write("				for(let i = 0; i < cateList.length; i++){\r\n");
      out.write("					if(cateList[i].tier === tier){\r\n");
      out.write("						obj = new Object();\r\n");
      out.write("						\r\n");
      out.write("						obj.cateName = cateList[i].cateName;\r\n");
      out.write("						obj.cateCode = cateList[i].cateCode;\r\n");
      out.write("						obj.cateParent = cateList[i].cateParent;\r\n");
      out.write("						\r\n");
      out.write("						array.push(obj);				\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			}	\r\n");
      out.write("			\r\n");
      out.write("			/* 배열 초기화 */\r\n");
      out.write("			makeCateArray(cate1Obj,cate1Array,cateList,1);\r\n");
      out.write("			makeCateArray(cate2Obj,cate2Array,cateList,2);\r\n");
      out.write("			makeCateArray(cate3Obj,cate3Array,cateList,3);\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			let targetCate2 = '';\r\n");
      out.write("			let targetCate3 = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.cateCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("			\r\n");
      out.write("			/* 소분류 */\r\n");
      out.write("			for(let i = 0; i < cate3Array.length; i++){\r\n");
      out.write("				if(targetCate3 === cate3Array[i].cateCode){\r\n");
      out.write("					targetCate3 = cate3Array[i];\r\n");
      out.write("				}\r\n");
      out.write("			}// for			\r\n");
      out.write("			\r\n");
      out.write("			for(let i = 0; i < cate3Array.length; i++){\r\n");
      out.write("				if(targetCate3.cateParent === cate3Array[i].cateParent){\r\n");
      out.write("					cateSelect3.append(\"<option value='\"+cate3Array[i].cateCode+\"'>\" + cate3Array[i].cateName + \"</option>\");\r\n");
      out.write("				}\r\n");
      out.write("			}				\r\n");
      out.write("			\r\n");
      out.write("			$(\".cate3 option\").each(function(i,obj){\r\n");
      out.write("				if(targetCate3.cateCode === obj.value){\r\n");
      out.write("					$(obj).attr(\"selected\", \"selected\");\r\n");
      out.write("				}\r\n");
      out.write("			});			\r\n");
      out.write("			\r\n");
      out.write("			/* 중분류 */\r\n");
      out.write("			for(let i = 0; i < cate2Array.length; i++){\r\n");
      out.write("				if(targetCate3.cateParent === cate2Array[i].cateCode){\r\n");
      out.write("					targetCate2 = cate2Array[i];	\r\n");
      out.write("				}\r\n");
      out.write("			}// for		\r\n");
      out.write("			\r\n");
      out.write("			for(let i = 0; i < cate2Array.length; i++){\r\n");
      out.write("				if(targetCate2.cateParent === cate2Array[i].cateParent){\r\n");
      out.write("					cateSelect2.append(\"<option value='\"+cate2Array[i].cateCode+\"'>\" + cate2Array[i].cateName + \"</option>\");\r\n");
      out.write("				}\r\n");
      out.write("			}		\r\n");
      out.write("			\r\n");
      out.write("			$(\".cate2 option\").each(function(i,obj){\r\n");
      out.write("				if(targetCate2.cateCode === obj.value){\r\n");
      out.write("					$(obj).attr(\"selected\", \"selected\");\r\n");
      out.write("				}\r\n");
      out.write("			});				\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			/* 대분류 */\r\n");
      out.write("			for(let i = 0; i < cate1Array.length; i++){\r\n");
      out.write("				cateSelect1.append(\"<option value='\"+cate1Array[i].cateCode+\"'>\" + cate1Array[i].cateName + \"</option>\");\r\n");
      out.write("			}	\r\n");
      out.write("			\r\n");
      out.write("			$(\".cate1 option\").each(function(i,obj){\r\n");
      out.write("				if(targetCate2.cateParent === obj.value){\r\n");
      out.write("					$(obj).attr(\"selected\", \"selected\");\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			/* 위지윅 적용 */\r\n");
      out.write("			 \r\n");
      out.write("			/* 책 소개 */\r\n");
      out.write("			ClassicEditor\r\n");
      out.write("				.create(document.querySelector('#bookIntro_textarea'))\r\n");
      out.write("				.catch(error=>{\r\n");
      out.write("					console.error(error);\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("			/* 책 목차 */	\r\n");
      out.write("			ClassicEditor\r\n");
      out.write("			.create(document.querySelector('#bookContents_textarea'))\r\n");
      out.write("			.catch(error=>{\r\n");
      out.write("				console.error(error);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			/* 할인율 인터페이스 출력 */\r\n");
      out.write("			let bookPriceInput = $(\"input[name='bookPrice']\");\r\n");
      out.write("			let discountInput = $(\"input[name='bookDiscount']\");\r\n");
      out.write("			\r\n");
      out.write("			let bookPrice = bookPriceInput.val();\r\n");
      out.write("			let rawDiscountRate = discountInput.val();\r\n");
      out.write("			let discountRate = rawDiscountRate * 100;\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			let discountPrice = bookPrice * (1-rawDiscountRate);\r\n");
      out.write("			$(\".span_discount\").html(discountPrice);\r\n");
      out.write("			$(\"#discount_interface\").val(discountRate);\r\n");
      out.write("			\r\n");
      out.write("			/* 기존 이미지 출력 */\r\n");
      out.write("			let bookId = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("			let uploadResult = $(\"#uploadResult\");\r\n");
      out.write("			\r\n");
      out.write("			$.getJSON(\"/getAttachList\", {bookId : bookId}, function(arr){\r\n");
      out.write("				\r\n");
      out.write("				console.log(arr);\r\n");
      out.write("				\r\n");
      out.write("				if(arr.length === 0){\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					let str = \"\";\r\n");
      out.write("					str += \"<div id='result_card'>\";\r\n");
      out.write("					str += \"<img src='/resources/img/goodsNoImage.png'>\";\r\n");
      out.write("					str += \"</div>\";\r\n");
      out.write("					\r\n");
      out.write("					uploadResult.html(str);				\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				let str = \"\";\r\n");
      out.write("				let obj = arr[0];\r\n");
      out.write("				\r\n");
      out.write("				let fileCallPath = encodeURIComponent(obj.uploadPath + \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("				str += \"<div id='result_card'\";\r\n");
      out.write("				str += \"data-path='\" + obj.uploadPath + \"' data-uuid='\" + obj.uuid + \"' data-filename='\" + obj.fileName + \"'\";\r\n");
      out.write("				str += \">\";\r\n");
      out.write("				str += \"<img src='/display?fileName=\" + fileCallPath +\"'>\";\r\n");
      out.write("				str += \"<div class='imgDeleteBtn' data-file='\" + fileCallPath + \"'>x</div>\";\r\n");
      out.write("				str += \"<input type='hidden' name='imageList[0].fileName' value='\"+ obj.fileName +\"'>\";\r\n");
      out.write("				str += \"<input type='hidden' name='imageList[0].uuid' value='\"+ obj.uuid +\"'>\";\r\n");
      out.write("				str += \"<input type='hidden' name='imageList[0].uploadPath' value='\"+ obj.uploadPath +\"'>\";				\r\n");
      out.write("				str += \"</div>\";\r\n");
      out.write("				\r\n");
      out.write("				uploadResult.html(str);			\r\n");
      out.write("				\r\n");
      out.write("			});// GetJSON\r\n");
      out.write("			\r\n");
      out.write("			/* 할인율 Input 설정 */\r\n");
      out.write("			\r\n");
      out.write("			$(\"#discount_interface\").on(\"propertychange change keyup paste input\", function(){\r\n");
      out.write("				\r\n");
      out.write("				let userInput = $(\"#discount_interface\");\r\n");
      out.write("				let discountInput = $(\"input[name='bookDiscount']\");\r\n");
      out.write("				\r\n");
      out.write("				let discountRate = userInput.val();					// 사용자가 입력한 할인값\r\n");
      out.write("				let sendDiscountRate = discountRate / 100;			// 서버에 전송할 할인값\r\n");
      out.write("				let goodsPrice = $(\"input[name='bookPrice']\").val();			// 원가\r\n");
      out.write("				let discountPrice = goodsPrice * (1 - sendDiscountRate);		// 할인가격\r\n");
      out.write("				\r\n");
      out.write("				if(!isNaN(discountRate)){\r\n");
      out.write("					$(\".span_discount\").html(discountPrice);		\r\n");
      out.write("					discountInput.val(sendDiscountRate);				\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			});	\r\n");
      out.write("			\r\n");
      out.write("			$(\"input[name='bookPrice']\").on(\"change\", function(){\r\n");
      out.write("				\r\n");
      out.write("				let userInput = $(\"#discount_interface\");\r\n");
      out.write("				let discountInput = $(\"input[name='bookDiscount']\");\r\n");
      out.write("				\r\n");
      out.write("				let discountRate = userInput.val();					// 사용자가 입력한 할인값\r\n");
      out.write("				let sendDiscountRate = discountRate / 100;			// 서버에 전송할 할인값\r\n");
      out.write("				let goodsPrice = $(\"input[name='bookPrice']\").val();			// 원가\r\n");
      out.write("				let discountPrice = goodsPrice * (1 - sendDiscountRate);		// 할인가격\r\n");
      out.write("				\r\n");
      out.write("				if(!isNaN(discountRate)){\r\n");
      out.write("					$(\".span_discount\").html(discountPrice);	\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	</script> \r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	/* 카테고리 */\r\n");
      out.write("	let cateList = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cateList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\r\n");
      out.write("	let cate1Array = new Array();\r\n");
      out.write("	let cate2Array = new Array();\r\n");
      out.write("	let cate3Array = new Array();\r\n");
      out.write("	let cate1Obj = new Object();\r\n");
      out.write("	let cate2Obj = new Object();\r\n");
      out.write("	let cate3Obj = new Object();\r\n");
      out.write("	\r\n");
      out.write("	let cateSelect1 = $(\".cate1\");		\r\n");
      out.write("	let cateSelect2 = $(\".cate2\");\r\n");
      out.write("	let cateSelect3 = $(\".cate3\");\r\n");
      out.write("	\r\n");
      out.write("	/* 카테고리 배열 초기화 메서드 */\r\n");
      out.write("	function makeCateArray(obj,array,cateList, tier){\r\n");
      out.write("		for(let i = 0; i < cateList.length; i++){\r\n");
      out.write("			if(cateList[i].tier === tier){\r\n");
      out.write("				obj = new Object();\r\n");
      out.write("				\r\n");
      out.write("				obj.cateName = cateList[i].cateName;\r\n");
      out.write("				obj.cateCode = cateList[i].cateCode;\r\n");
      out.write("				obj.cateParent = cateList[i].cateParent;\r\n");
      out.write("				\r\n");
      out.write("				array.push(obj);				\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}	\r\n");
      out.write("	\r\n");
      out.write("		/* 배열 초기화 */\r\n");
      out.write("	makeCateArray(cate1Obj,cate1Array,cateList,1);\r\n");
      out.write("	makeCateArray(cate2Obj,cate2Array,cateList,2);\r\n");
      out.write("	makeCateArray(cate3Obj,cate3Array,cateList,3);\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		/* 중분류 <option> 태그 */\r\n");
      out.write("	$(cateSelect1).on(\"change\",function(){\r\n");
      out.write("		\r\n");
      out.write("		let selectVal1 = $(this).find(\"option:selected\").val();	\r\n");
      out.write("		\r\n");
      out.write("		cateSelect2.children().remove();\r\n");
      out.write("		cateSelect3.children().remove();\r\n");
      out.write("		\r\n");
      out.write("		cateSelect2.append(\"<option value='none'>선택</option>\");\r\n");
      out.write("		cateSelect3.append(\"<option value='none'>선택</option>\");\r\n");
      out.write("		\r\n");
      out.write("		for(let i = 0; i < cate2Array.length; i++){\r\n");
      out.write("			if(selectVal1 === cate2Array[i].cateParent){\r\n");
      out.write("				cateSelect2.append(\"<option value='\"+cate2Array[i].cateCode+\"'>\" + cate2Array[i].cateName + \"</option>\");	\r\n");
      out.write("			}\r\n");
      out.write("		}// for\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("		/* 소분류 <option>태그 */\r\n");
      out.write("	$(cateSelect2).on(\"change\",function(){\r\n");
      out.write("		\r\n");
      out.write("		let selectVal2 = $(this).find(\"option:selected\").val();\r\n");
      out.write("		\r\n");
      out.write("		cateSelect3.children().remove();\r\n");
      out.write("		\r\n");
      out.write("		cateSelect3.append(\"<option value='none'>선택</option>\");		\r\n");
      out.write("		\r\n");
      out.write("		for(let i = 0; i < cate3Array.length; i++){\r\n");
      out.write("			if(selectVal2 === cate3Array[i].cateParent){\r\n");
      out.write("				cateSelect3.append(\"<option value='\"+cate3Array[i].cateCode+\"'>\" + cate3Array[i].cateName + \"</option>\");	\r\n");
      out.write("			}\r\n");
      out.write("		}// for		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	/* 취소 버튼 */\r\n");
      out.write("	$(\"#cancelBtn\").on(\"click\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		$(\"#moveForm\").submit();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 삭제 버튼 */\r\n");
      out.write("	$(\"#deleteBtn\").on(\"click\", function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		let moveForm = $(\"#moveForm\");\r\n");
      out.write("		moveForm.find(\"input\").remove();\r\n");
      out.write("		moveForm.append('<input type=\"hidden\" name=\"bookId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">');\r\n");
      out.write("		moveForm.attr(\"action\", \"/admin/goodsDelete\");\r\n");
      out.write("		moveForm.attr(\"method\", \"post\");\r\n");
      out.write("		moveForm.submit();\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 수정 버튼 */\r\n");
      out.write("	$(\"#modifyBtn\").on(\"click\",function(e){\r\n");
      out.write("		\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		\r\n");
      out.write("		/* 체크 변수 */\r\n");
      out.write("		let bookNameCk = false;\r\n");
      out.write("		let authorIdCk = false;\r\n");
      out.write("		let publeYearCk = false;\r\n");
      out.write("		let publisherCk = false;\r\n");
      out.write("		let cateCodeCk = false;\r\n");
      out.write("		let priceCk = false;\r\n");
      out.write("		let stockCk = false;\r\n");
      out.write("		let discountCk = false;\r\n");
      out.write("		let introCk = false;\r\n");
      out.write("		let contentsCk = false;	\r\n");
      out.write("		\r\n");
      out.write("		/* 체크 대상 변수 */\r\n");
      out.write("		let bookName = $(\"input[name='bookName']\").val();\r\n");
      out.write("		let authorId = $(\"input[name='authorId']\").val();\r\n");
      out.write("		let publeYear = $(\"input[name='publeYear']\").val();\r\n");
      out.write("		let publisher = $(\"input[name='publisher']\").val();\r\n");
      out.write("		let cateCode = $(\"select[name='cateCode']\").val();\r\n");
      out.write("		let bookPrice = $(\"input[name='bookPrice']\").val();\r\n");
      out.write("		let bookStock = $(\"input[name='bookStock']\").val();\r\n");
      out.write("		let bookDiscount = $(\"#discount_interface\").val();\r\n");
      out.write("		let bookIntro = $(\".bit p\").html();\r\n");
      out.write("		let bookContents = $(\".bct p\").html();	\r\n");
      out.write("		\r\n");
      out.write("		/* 공란 체크 */\r\n");
      out.write("		if(bookName){\r\n");
      out.write("			$(\".bookName_warn\").css('display','none');\r\n");
      out.write("			bookNameCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".bookName_warn\").css('display','block');\r\n");
      out.write("			bookNameCk = false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(authorId){\r\n");
      out.write("			$(\".authorId_warn\").css('display','none');\r\n");
      out.write("			authorIdCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".authorId_warn\").css('display','block');\r\n");
      out.write("			authorIdCk = false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(publeYear){\r\n");
      out.write("			$(\".publeYear_warn\").css('display','none');\r\n");
      out.write("			publeYearCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".publeYear_warn\").css('display','block');\r\n");
      out.write("			publeYearCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("		if(publisher){\r\n");
      out.write("			$(\".publisher_warn\").css('display','none');\r\n");
      out.write("			publisherCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".publisher_warn\").css('display','block');\r\n");
      out.write("			publisherCk = false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(cateCode != 'none'){\r\n");
      out.write("			$(\".cateCode_warn\").css('display','none');\r\n");
      out.write("			cateCodeCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".cateCode_warn\").css('display','block');\r\n");
      out.write("			cateCodeCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("		if(bookPrice != 0){\r\n");
      out.write("			$(\".bookPrice_warn\").css('display','none');\r\n");
      out.write("			priceCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".bookPrice_warn\").css('display','block');\r\n");
      out.write("			priceCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("		if(bookStock != 0){\r\n");
      out.write("			$(\".bookStock_warn\").css('display','none');\r\n");
      out.write("			stockCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".bookStock_warn\").css('display','block');\r\n");
      out.write("			stockCk = false;\r\n");
      out.write("		}		\r\n");
      out.write("		\r\n");
      out.write("		if(!isNaN(bookDiscount)){\r\n");
      out.write("			$(\".bookDiscount_warn\").css('display','none');\r\n");
      out.write("			discountCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".bookDiscount_warn\").css('display','block');\r\n");
      out.write("			discountCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("		if(bookIntro != '<br data-cke-filler=\"true\">'){\r\n");
      out.write("			$(\".bookIntro_warn\").css('display','none');\r\n");
      out.write("			introCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".bookIntro_warn\").css('display','block');\r\n");
      out.write("			introCk = false;\r\n");
      out.write("		}	\r\n");
      out.write("		\r\n");
      out.write("		if(bookContents != '<br data-cke-filler=\"true\">'){\r\n");
      out.write("			$(\".bookContents_warn\").css('display','none');\r\n");
      out.write("			contentsCk = true;\r\n");
      out.write("		} else {\r\n");
      out.write("			$(\".bookContents_warn\").css('display','block');\r\n");
      out.write("			contentsCk = false;\r\n");
      out.write("		}		\r\n");
      out.write("		\r\n");
      out.write("		/* 최종 확인 */\r\n");
      out.write("		if(bookNameCk && authorIdCk && publeYearCk && publisherCk && cateCodeCk && priceCk && stockCk && discountCk && introCk && contentsCk ){\r\n");
      out.write("			//alert('통과');\r\n");
      out.write("			$(\"#modifyForm\").submit();\r\n");
      out.write("		} else {\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/* 이미지 삭제 버튼 동작 */\r\n");
      out.write("	$(\"#uploadResult\").on(\"click\", \".imgDeleteBtn\", function(e){\r\n");
      out.write("		\r\n");
      out.write("		deleteFile();\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	/* 파일 삭제 메서드 */\r\n");
      out.write("	function deleteFile(){\r\n");
      out.write("		\r\n");
      out.write("		$(\"#result_card\").remove();\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 이미지 업로드 */\r\n");
      out.write("	$(\"input[type='file']\").on(\"change\", function(e){\r\n");
      out.write("		\r\n");
      out.write("		/* 이미지 존재시 삭제 */\r\n");
      out.write("		if($(\"#result_card\").length > 0){\r\n");
      out.write("			deleteFile();\r\n");
      out.write("		}\r\n");
      out.write("				\r\n");
      out.write("		let formData = new FormData();\r\n");
      out.write("		let fileInput = $('input[name=\"uploadFile\"]');\r\n");
      out.write("		let fileList = fileInput[0].files;\r\n");
      out.write("		let fileObj = fileList[0];\r\n");
      out.write("		\r\n");
      out.write("		if(!fileCheck(fileObj.name, fileObj.size)){\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		formData.append(\"uploadFile\", fileObj);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: '/admin/uploadAjaxAction',\r\n");
      out.write("	    	processData : false,\r\n");
      out.write("	    	contentType : false,\r\n");
      out.write("	    	data : formData,\r\n");
      out.write("	    	type : 'POST',\r\n");
      out.write("	    	dataType : 'json',\r\n");
      out.write("	    	success : function(result){\r\n");
      out.write("	    		console.log(result);\r\n");
      out.write("	    		showUploadImage(result);\r\n");
      out.write("	    	},\r\n");
      out.write("	    	error : function(result){\r\n");
      out.write("	    		alert(\"이미지 파일이 아닙니다.\");\r\n");
      out.write("	    	}\r\n");
      out.write("		});		\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	/* var, method related with attachFile */\r\n");
      out.write("	let regex = new RegExp(\"(.*?)\\.(jpg|png)$\");\r\n");
      out.write("	let maxSize = 1048576; //1MB	\r\n");
      out.write("	\r\n");
      out.write("	function fileCheck(fileName, fileSize){\r\n");
      out.write("\r\n");
      out.write("		if(fileSize >= maxSize){\r\n");
      out.write("			alert(\"파일 사이즈 초과\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("			  \r\n");
      out.write("		if(!regex.test(fileName)){\r\n");
      out.write("			alert(\"해당 종류의 파일은 업로드할 수 없습니다.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		return true;		\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* 이미지 출력 */\r\n");
      out.write("	function showUploadImage(uploadResultArr){\r\n");
      out.write("		\r\n");
      out.write("		/* 전달받은 데이터 검증 */\r\n");
      out.write("		if(!uploadResultArr || uploadResultArr.length == 0){return}\r\n");
      out.write("		\r\n");
      out.write("		let uploadResult = $(\"#uploadResult\");\r\n");
      out.write("		\r\n");
      out.write("		let obj = uploadResultArr[0];\r\n");
      out.write("		\r\n");
      out.write("		let str = \"\";\r\n");
      out.write("		\r\n");
      out.write("		let fileCallPath = encodeURIComponent(obj.uploadPath.replace(/\\\\/g, '/') + \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("		//replace 적용 하지 않아도 가능\r\n");
      out.write("		//let fileCallPath = encodeURIComponent(obj.uploadPath + \"/s_\" + obj.uuid + \"_\" + obj.fileName);\r\n");
      out.write("		\r\n");
      out.write("		str += \"<div id='result_card'>\";\r\n");
      out.write("		str += \"<img src='/display?fileName=\" + fileCallPath +\"'>\";\r\n");
      out.write("		str += \"<div class='imgDeleteBtn' data-file='\" + fileCallPath + \"'>x</div>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].fileName' value='\"+ obj.fileName +\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].uuid' value='\"+ obj.uuid +\"'>\";\r\n");
      out.write("		str += \"<input type='hidden' name='imageList[0].uploadPath' value='\"+ obj.uploadPath +\"'>\";		\r\n");
      out.write("		str += \"</div>\";		\r\n");
      out.write("		\r\n");
      out.write("   		uploadResult.append(str);     \r\n");
      out.write("        \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/admin/goodsModify.jsp(316,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goodsInfo.bookId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
